### PR TITLE
Admin page

### PR DESCRIPTION
**Pull request by MHG16**
I created the Admin page that will allow Admins to add Teachers.  Please look it over.

### CODE REVIEW

**Comment by willcook4code** [comment]
👍

**Comment by NJHawthorne** [comment]
👍  noice!

**Comment by alarner** [comment]
Needs error messages, api url is not quite right.

**Comment by MHG16** [comment]
Admin page now has the correct url and  displays an error message if a an email address of an existing Teacher is used.  Also added a modal to display when Teacher successfully created.

**Comment by hammour** [comment]
👍

**Comment by ihatetoast** [comment]
👍

**Comment by NJHawthorne** [comment]
I stand by my noice comment earlier, but 👍  all the same.

**Pull request merged**
