### PR TITLE
Fetch stories

### PR DESCRIPTION
**Pull request by ihatetoast**
It's not ready for a merge, but it's in rough draft form and ready for eyes. Those in charge of the tangental components please have a look-see to see what I need to do for it to work. (Dan? Will?)

### CODE REVIEW

**Comment by alarner** [comment]
This looks good to me as long as `CategoriesPreview` exists

**Comment by alarner** [comment]
👍 looks good

**Comment by willcook4code** [comment]
👍

**Comment by joshwerner85** [comment]
👍

**Pull request merged**
