### PR TITLE
Global and category styles

### PR DESCRIPTION
**Pull request by tinydinosaurs**
I've got some global and category styles ready. They're based on the colors and typography Jenina provided us in her style tile. The styles aren't complete, but I don't think anything will break if we merge.

### CODE REVIEW

**Comment by hammour** [comment]
👍

**Comment by alarner** [comment]
Be sure to make sure you're using tabs not spaces. Also it looks like you also have your navigation in this pull request. You might have created a branch from your navigation branch instead of from master. Should be fine but you might want to merge in your navigation component code first

**Comment by hammour** [comment]
👍

**Comment by alarner** [comment]
@tinydinosaurs is this a duplicate branch to #30 ?

**Pull request closed without merging**
