### PR TITLE
Style read view pt2

### PR DESCRIPTION
**Pull request by willcook4code**
Please take a look at my styles for the read page.  Open to further suggestions.

### CODE REVIEW

**Comment by NJHawthorne** [comment]
It looks like a lot of the styles you're using are also being used by Jen in her latest pull request, so I'm not sure if I should thumbs this up as well, just for the sake of avoiding more merge conflicts and repetition.

**Comment by willcook4code** [comment]
Some of the styles were pushed earlier.  So all who have updated pull requests should have them.

**Comment by DanBuda11** [comment]
👍

**Comment by tinydinosaurs** [comment]
👍

**Comment by hammour** [comment]
:+1:

**Pull request merged**
