### PR TITLE
Navigation updates

### PR DESCRIPTION
**Pull request by tinydinosaurs**
Navigation contains "add users" link if logged in as admin; logo points to "/" when logged out and "/stories" when logged in; logged in navigation also has a separate link for stories.

### CODE REVIEW

**Comment by NJHawthorne** [comment]
I'll give this a thumbs up if you remove the console.log on line 24. Other than that, looks good to me.

**Comment by judan** [comment]
💯

**Comment by MHG16** [comment]
👍

**Comment by willcook4code** [comment]
👍

**Pull request merged**
