### PR TITLE
Added ReadPage component and updated router

### PR DESCRIPTION
**Pull request by NJHawthorne**
Hey guys. Look, more code! Give it a big ol' thumbs up if you're feeling fine and dandy.

### CODE REVIEW

**Comment by willcook4code** [comment]
I think ReadPage should be called "Read" for consistencies' sake.

**Comment by judan** [comment]
💯

**Comment by alarner** [comment]
The path of the route should ultimately be /story/(story_id)/read. There mighe be another ticket for that part of the router work, but just double check that. If there is not another ticket you will need to do that. You can read see an example of something like that being done here:

https://github.com/reactjs/react-router/blob/master/examples/query-params/app.js

You can read up more on it here:

https://github.com/reactjs/react-router/blob/master/docs/guides/RouteMatching.md

**Comment by willcook4code** [comment]
👍

**Comment by joshwerner85** [comment]
👍

**Pull request merged**
