### PR TITLE
data model and BE story model

### PR DESCRIPTION
**Pull request by afmonty**
The data model link should be in the read me file.  I have also added the backend story model.

### CODE REVIEW

**Comment by alarner** [comment]
It looks like the capitalization is off when you're inserting your data model png file into the README so it's not showing up. The rest looks great

This has been corrected

**Comment by tinydinosaurs** [comment]
👍

**Comment by NJHawthorne** [comment]
👍

**Comment by Moryf1990** [comment]
👍

**Comment by willcook4code** [comment]
Looks good except the 'story.js' file should be capitalized for consistency of other files of the type.

**Comment by NJHawthorne** [comment]
👍  👍  👍

**Comment by hammour** [comment]
👍

**Comment by Moryf1990** [comment]
👍

**Comment by willcook4code** [comment]
👍

**Pull request merged**
