### PR TITLE
Create details page

### PR DESCRIPTION
**Pull request by willcook4code**
I created the barebones for details page and the router line in main.js.  I can merge now?

### CODE REVIEW

**Comment by NJHawthorne** [comment]
👎  your route path should be "details" rather than "stories"

**Comment by willcook4code** [comment]
Corrected the path to 'details' in main.js.  Please take another look and forgive my transgressions.

**Comment by NJHawthorne** [comment]
👍

**Comment by Moryf1990** [comment]
👍

**Comment by afmonty** [comment]
👍

**Pull request merged**
