### PR TITLE
Add git/github workflow steps to readme

### PR DESCRIPTION
**Pull request by alarner**
I've added a bunch of steps that explain the workflow that we are using to the README file.

### CODE REVIEW

**Comment by NicerHugs** [comment]
👎 pls make the numbered steps actually numbers, OR change them to dashes/bullets.

**Comment by alarner** [comment]
Just updated the numbers to be correct. Thanks @NicerHugs !

**Comment by NJHawthorne** [comment]
👍

**Comment by tinydinosaurs** [comment]
👍

**Comment by willcook4code** [comment]
👍

**Pull request merged**
