### PR TITLE
Add student modal

### PR DESCRIPTION
**Pull request by afmonty**
I created the student pop up with the post to the server.  I had to delete the id default from the two front end models because it was causing errors when trying to write to the db.  No errors but needs to be styled.

### CODE REVIEW

**Comment by willcook4code** [comment]
It would appear that your branch has conflicts because the yieldy sign thingy says "This branch has conflicts that must be resolved".  Seeing as how I did this earlier today, I can tell you that you probably need to pull from the master before pushing again?

**Comment by willcook4code** [comment]
👍

**Comment by DanBuda11** [comment]
👍

**Comment by MHG16** [comment]
👍

**Pull request merged**
