### PR TITLE
Adding Front End model for the stories

### PR DESCRIPTION
**Pull request by NJHawthorne**
Here's the code for our front-end model of the stories. Take a look, folks. Give opinions. Give criticism. Give candy. Whatever works.

### CODE REVIEW

**Comment by judan** [comment]
💯

**Comment by NJHawthorne** [comment]
Updated the story model and added the collection for the Front End's stories stuff. So I'm resetting the counter to 0. Take a look and tell me what ya think.

**Comment by hammour** [comment]
👍

**Comment by tinydinosaurs** [comment]
💯  looks good hooray

**Comment by alarner** [comment]
Looks great. My only comment would be that you probably don't need the `deletedAt` attribute in your front-end models, because deleted records should never show up on the front-end.

**Pull request merged**
