### PR TITLE
frontend user model built out

### PR DESCRIPTION
**Pull request by joshwerner85**
The front end user model is built out please check my code and give me a thumbs up.

### CODE REVIEW

**Comment by judan** [comment]
💯

**Comment by tinydinosaurs** [comment]
👎  Errors: 
- `createAt` should be `createdAt` 
- add `rootUrl` and `idAttribute`values
- fix typo in comment

**Comment by joshwerner85** [comment]
Everything is updated and correct.

**Comment by willcook4code** [comment]
👎  Need idAttribute: 'id'

**Comment by alarner** [comment]
Also it should be urlRoot not rootUrl

**Comment by joshwerner85** [comment]
Everything is has been double checked and corrected where needed.

**Comment by willcook4code** [comment]
👍

**Comment by NJHawthorne** [comment]
👍

**Comment by tinydinosaurs** [comment]
👍  @joshwerner85

**Pull request merged**
