### PR TITLE
Login component 

### PR DESCRIPTION
**Pull request by zamariac**
Created login router and component.
Styled to the balsamiq mock up.

### CODE REVIEW

**Comment by NJHawthorne** [comment]
My only concern is that we might want to wrap the inputs and button with a 'form' tag rather than a 'div'. Other than that, looks awesome!

**Comment by alarner** [comment]
Yes I'd echo @NJHawthorne. Also you might want to think about where error message might go if there are problems logging in. Also the type of your password element should be "password" not "text". For example...

``` html
<form className="login-box">
    <div className="form-row">
        <input type="text" placeholder="email"/>
        <div className="error"></div>
    </div>
    <div className="form-row">
        <input type="password" placeholder="password"/>
        <div className="error"></div>
    </div>
</div>
```

**Comment by zamariac** [comment]
Added a form element to the component and placed error message holders. need one more thumbs up to merge to the master!

**Comment by NJHawthorne** [comment]
👍

**Comment by willcook4code** [comment]
👍

**Comment by judan** [comment]
👎  Need to use Skeleton class names for the form. See Dana for more about this.

**Comment by hammour** [comment]
👍

**Pull request merged**
